### ISSUE TITLE
chrome插件

### ISSUE THREAD

**Issue by zcker** [circlestarzero/EX-chatGPT#1]
老板能不能打包一下你魔改的chrome插件啊，方便一点，自己Build好麻烦的，谢谢
还希望能完善一下readme，怎么使用还是不清楚，谢谢

**Comment by T-OvO-T** [comment]
> 我复现成功了，稍后写一篇文字详细讲解一下。

请教下，文字详解在哪里看哈

**Comment by T-OvO-T** [comment]
> 老板能不能打包一下你魔改的chrome插件啊，方便一点，自己Build好麻烦的，谢谢 还希望能完善一下readme，怎么使用还是不清楚，谢谢

请问你会使用了吗，麻烦教一教
