### ISSUE TITLE
我怎么部署这个项目

### ISSUE THREAD

**Issue by fang88i8** [circlestarzero/EX-chatGPT#11]
我对这个东西特别感兴趣，但是没有相关任何经验，作者可以回复我一下吗？我可以赞助

**Comment by circlestarzero** [comment]
https://blog.lty.wiki/index.php/archives/41/

**Comment by learnCodeON** [comment]
我的一些经验：
1、打开openai官网时，遇到”OpenAI's services are not available in your country“时，博客园有一个文章可以解决：https://www.cnblogs.com/aiyablog/p/16989556.html。建议每次进入openai官网时，都进行该文章中的操作
2、打开openai官网时，我遇到过一个奇怪的错误（当时我没有截图，不记得是什么错误了），更换加速器的节点。
3、遇到gmail邮箱不能注册时，打开加速器（我当时是选择的美国节点），把浏览器的语言改成”英语（美国）“，电话号码写你自己的也行，这样就能在gmail里面注册了。
4、该项目中，SEARCH_ENGINE_ID填写的是“Custom Search API”，至于怎么申请它，circlestarzero已经给你答案了。“Custom Search API”每天只能免费查询100次，即100次免费的搜索功能。其他的api key不用担心收费和次数的问题（因为其他的每天的使用次数很多）。在申请了“Custom Search API”之后，用gmail登录“google console”，在“google console”搜索“Custom Search API”，或者进入“https://console.cloud.google.com/apis/api/customsearch.googleapis.com/”，点击那个页面的“QUOTAS”，在“filter”里面的“Queries per day”可以看自己用了多少查询次数。“Custom Search API”可能会涉及收费问题，它超出100次的部分，每1000次查询要5美元，你可以不用管，因为如果没有绑定支付账户就不会扣钱。

**Comment by fang88i8** [comment]
多个端口一起看的时候特别慢
