### ISSUE TITLE
我想知道"Google search engine id"的收费情况

### ISSUE THREAD

**Issue by learnCodeON** [circlestarzero/EX-chatGPT#12]
"Google search engine id"的收费情况是怎么样的？还有，我在问ChatGPT关于"Google search engine id"的收费情况时，他说：“在使用Google Custom Search Engine API时，每天可以进行100个请求（即每天可以搜索100次）。 如果超过这个限制，则需要支付相应的费用”，这个是真的吗？

**Comment by learnCodeON** [comment]
还有一个问题，请问你说的"Google search engine id"指的是"Custom Search JSON API"还是"Google Custom Search Engine API"？

**Comment by circlestarzero** [comment]
5$ per 1000 requests 
Google Custom Search Engine API
中文教程:https://blog.lty.wiki/index.php/archives/41/
