### ISSUE TITLE
多轮搜索

### ISSUE THREAD

**Issue by ProblemFactory** [circlestarzero/EX-chatGPT#16]
有些时候机器人可能需要一轮搜索来明确接下来调用的API，然后才能继续完成请求。现在的机器人可以支持多轮搜索吗？
另外能不能增加让机器人直接访问网页来获取资料的能力？比如第一轮搜索得到了URL1是可能有帮助的，第二轮可以让机器人要求直接访问URL1来获得里面的内容？

**Comment by circlestarzero** [comment]
是支持多轮的, 访问页面爬数据的功能在schedule上

**Comment by ProblemFactory** [comment]
是指detail模式吗？可以在readme里大概介绍一下每个模式的区别吗？实在有点分不清

**Comment by circlestarzero** [comment]
已经添加了介绍
