### ISSUE TITLE
Wrong language for web results? 

### ISSUE THREAD

**Issue by batsking** [circlestarzero/EX-chatGPT#19]
Installed the website

All the ui is english
Chat responses are in english

But when using web:

![SmartSelect_20230309_002126_Iceraven](https://user-images.githubusercontent.com/97805786/223864875-0e681579-e508-4144-a33a-53fb60a969b8.jpg)

Thanks

**Comment by AsafMah** [comment]
Thank you!

**Comment by circlestarzero** [comment]
fixed，add auto language detect mode
