### ISSUE TITLE
上下文记忆

### ISSUE THREAD

**Issue by CALMCRAZY** [circlestarzero/EX-chatGPT#2]
请教一下，虽然实现了调用API的功能，但失去了上下文记忆？变成单次问答了？

**Comment by ProblemFactory** [comment]
看起来是这个样子的。我觉得可以在每次prompt里插入之前的对话历史来保留上下文能力。

**Comment by CALMCRAZY** [comment]
> 看起来是这个样子的。我觉得可以在每次prompt里插入之前的对话历史来保留上下文能力。

确实，看别人调用gpt-3.5-turbo API的demo也是这么做的。但模型最多处理4096 token，包括输入和输出，这个项目里光是引导chatgpt调用API的prompt已经占用了很多token了，再插入对话历史留给输出的token就寥寥无几了

**Comment by JamesFlare1212** [comment]
一种办法是超出token之后把前面的对话概括后再发送，不过这样API燃烧地很快吧。

**Comment by circlestarzero** [comment]
![84B0063BBD491FB5DC75F4E0A331E72C](https://user-images.githubusercontent.com/75794159/222885498-cd76668c-1c13-4233-8f98-0b879617fdf9.jpg)

**Comment by circlestarzero** [comment]
> 

这个问题解决了

**Comment by circlestarzero** [comment]
> 看起来是这个样子的。我觉得可以在每次prompt里插入之前的对话历史来保留上下文能力。

是的，已经这样实现了
