### ISSUE TITLE
项目部署出错

### ISSUE THREAD

**Issue by onecombo** [circlestarzero/EX-chatGPT#32]
个人自我评价：小白+
经过十几小时的研究，大佬的项目依旧不能在我本地端成功使用，故而希望得到帮助。
**目前问题出现环节：成功进入界面，但chat回复文字为空，只有cost。**
部署环境：CentOS  7.9.2009+docker，另外这个系统平时也在跑宝塔。
后台日志：
![image](https://user-images.githubusercontent.com/33618120/224542207-7743c003-a229-4baa-8975-db32809e5f80.png)
分析可能的原因：配置文件不正确。当前的apikey.ini如下，字符以处理。
![image](https://user-images.githubusercontent.com/33618120/224542404-e6f02488-eb81-4f78-8408-cae5b69ce785.png)
已经尝试解决方式：
1，今天看到大佬更新了docker-compose.yaml，里面多了环境变量预设，我对项目了解不深入，不知道这里面的key：value是否需要对应apikey.ini中的key：value，所以尝试填写了一下。改动变为下图，问题没有得到解决，
![image](https://user-images.githubusercontent.com/33618120/224542595-482530e6-c83a-4136-8517-69c69c0254ca.png)
2，百度找到了类似问题的解决方案，得到原因是因为urllib3包版本太高的原因，尝试在requirements.txt中添加urllib3==1.25.11，重新拉取镜像，问题依旧。
另：大佬readme中的命令我这边本地没办法适用，后台日志报权限问题，我都是为容器挂载了一个虚拟存储才能打开127.0.0.1:5000。

猜测：可能还是apikey.ini和docker-compose.yaml发生的问题，如果是的话，能否请大佬为我讲解一下这其中的关系？不胜感激。

**Comment by acdiost** [comment]
1. docker-compose 中的环境变量暂时还是 TODO, 不影响。
2. 如果你的服务器不在境内，就可以直接使用；如果在国内则需要配置代理才可以访问

**Comment by onecombo** [comment]
> 1. docker-compose 中的环境变量暂时还是 TODO, 不影响。
> 2. 如果你的服务器不在境内，就可以直接使用；如果在国内则需要配置代理才可以访问

原来如此，这个代理原来是科学上网的代理，我以为api没有限制，感谢大佬解答。

**Comment by acdiost** [comment]
不是科学上网的代理。

**Comment by onecombo** [comment]
> 不是科学上网的代理。
我之前在git上偶然间看到了openai代理相关的项目，是一个挂在腾讯云上的云函数，我还纳闷这样做的目的。
原来代理是这样的代理。
我搞明白了，再次谢谢大佬。
