### ISSUE TITLE
关于回答中的引用

### ISSUE THREAD

**Issue by ProblemFactory** [circlestarzero/EX-chatGPT#5]
希望可以在最后回答中加入new bing那样的引用能力，这个我直接和chatgpt测试了下，应该是可行的。
![IMG_20230304_190907_033](https://user-images.githubusercontent.com/2966492/222939591-6c06820f-a216-40bc-bed7-fb3146ab2e8c.jpg)

另外希望可以不要总是说根据来自API的结果，而是直接说来自于什么网站或服务，然后给出引用。

**Comment by circlestarzero** [comment]
最开始有做，主要问题是会占用token

**Comment by circlestarzero** [comment]
这个模式已经更新了, webkeyword

**Comment by ProblemFactory** [comment]
webkeyword好像不是干这个的吧？
![image](https://user-images.githubusercontent.com/2966492/222965663-eaeadb60-8840-446a-90ff-27b25ddadbae.png)
