### ISSUE TITLE
总是产生中文结果，并且会附带无关信息

### ISSUE THREAD

**Issue by ProblemFactory** [circlestarzero/EX-chatGPT#7]
如图所示，不知道为啥结果总是中文的，而且会把推理过程也输出出来
![image](https://user-images.githubusercontent.com/2966492/222951281-44c57386-1cfa-4e6f-a3ca-cea39d19c9a7.png)

![image](https://user-images.githubusercontent.com/2966492/222951305-9bf5db0d-dd77-4790-9783-6c6230e8f033.png)

**Comment by circlestarzero** [comment]
在prompt里面改, 那个summary里面

**Comment by circlestarzero** [comment]
现在更新应该解决了, 结果输出在replysummary.txt里面改
